#:schema node_modules/wrangler/config-schema.json
name = "sublink-workersss"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "a8165fd149df4478ac681a2910d3ab32" }
]
